apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: bootstrap/argo-cd
    repoURL: https://github.com/awetomaton/sc-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
